# Generated by Django 3.2.7 on 2021-09-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='end',
        ),
        migrations.RemoveField(
            model_name='special',
            name='start',
        ),
        migrations.AddField(
            model_name='special',
            name='end_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='special',
            name='end_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='special',
            name='start_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='special',
            name='start_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
