# Generated by Django 3.2.7 on 2021-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0002_auto_20210927_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='end_time',
            field=models.TimeField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='special',
            name='start_time',
            field=models.TimeField(default=0, max_length=50),
        ),
    ]
