# Generated by Django 3.2.7 on 2021-09-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0003_auto_20210927_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='end_time',
            field=models.FloatField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name='special',
            name='start_time',
            field=models.FloatField(default=0.0, max_length=50),
        ),
    ]
